"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class robot_location_t(object):
    __slots__ = ["quat", "pos_vo"]

    __typenames__ = ["double", "double"]

    __dimensions__ = [[4], [3]]

    def __init__(self):
        self.quat = [ 0.0 for dim0 in range(4) ]
        self.pos_vo = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(robot_location_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>4d', *self.quat[:4]))
        buf.write(struct.pack('>3d', *self.pos_vo[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_location_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_location_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = robot_location_t()
        self.quat = struct.unpack('>4d', buf.read(32))
        self.pos_vo = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if robot_location_t in parents: return 0
        tmphash = (0xc6e99e336d284369) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if robot_location_t._packed_fingerprint is None:
            robot_location_t._packed_fingerprint = struct.pack(">Q", robot_location_t._get_hash_recursive([]))
        return robot_location_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", robot_location_t._get_packed_fingerprint())[0]

